#######
# Compiled from /smash_lib/functions/invulnerable.mcscript
# to .//smash_lib/functions/invulnerable/invulnerable.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add smash_lib_invulnerable
data merge entity @s[type=item] {Invulnerable:1b}
