#######
# Compiled from /smash_lib/functions/main.mcscript
# to .//smash_lib/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
#examples
function smash_lib:example

function smash_lib:detect
function smash_lib:action/main